services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: tourist_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/tourist_platform
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
    depends_on: [postgres, redis]
    volumes:
      - ./apps/api:/app
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
