"""Create guide profiles table

Revision ID: 956ac4009455
Revises: 001
Create Date: 2025-09-11 01:51:45.808467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956ac4009455'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_profiles_id'), 'guide_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_guide_profiles_user_id'), 'guide_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guide_profiles_user_id'), table_name='guide_profiles')
    op.drop_index(op.f('ix_guide_profiles_id'), table_name='guide_profiles')
    op.drop_table('guide_profiles')
    # ### end Alembic commands ###