"""Create tourist profiles and update guide profiles

Revision ID: d524fd7b07cc
Revises: f2399243cea9
Create Date: 2025-09-11 12:27:49.372562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd524fd7b07cc'
down_revision = 'f2399243cea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourist_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('home_city', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('spoken_languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tourist_profiles_id'), 'tourist_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_tourist_profiles_user_id'), 'tourist_profiles', ['user_id'], unique=True)
    op.add_column('guide_profiles', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('guide_profiles', sa.Column('guide_experience_years', sa.Integer(), nullable=True))
    op.add_column('guide_profiles', sa.Column('spoken_languages', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('guide_profiles', 'country')
    op.drop_column('guide_profiles', 'languages')
    op.drop_column('guide_profiles', 'experience_years')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guide_profiles', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('guide_profiles', sa.Column('languages', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('guide_profiles', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('guide_profiles', 'spoken_languages')
    op.drop_column('guide_profiles', 'guide_experience_years')
    op.drop_column('guide_profiles', 'full_name')
    op.drop_index(op.f('ix_tourist_profiles_user_id'), table_name='tourist_profiles')
    op.drop_index(op.f('ix_tourist_profiles_id'), table_name='tourist_profiles')
    op.drop_table('tourist_profiles')
    # ### end Alembic commands ###